### ISSUE TITLE
vem som helst kan handcuffa?!??!

### ISSUE THREAD

**Issue by ElPumpo** [kockeNN/esx_f5meny#1]
ingen QA i koden ju

**Comment by kockeNN** [comment]
Yes, vad annars, vem ''specifikt'' skulle kunna handcuffa då?

**Comment by HawaiiBeach** [comment]
lägg till en handcuff item eller något??? nu kan vem som helst oavsett om hen är fängslad eller död fängsla närmaste spelaren.

**Comment by kockeNN** [comment]
Om du kollar server.lua så är det redan klart nästintill, tar 1 sec att fixa, meningen är att inte allt ska vara serverat på ett silverfat.

**Comment by HawaiiBeach** [comment]
värdelöst
